apiVersion: apps/v1
kind: Deployment

metadata:
  name: customer-transaction-ml
  labels:
    app: customer-transaction-ml

spec:
  replicas: 2

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

  selector:
    matchLabels:
      app: customer-transaction-ml

  template:
    metadata:
      labels:
        app: customer-transaction-ml

    spec:
      containers:
        - name: customer-transaction-api

          # We will replace this with the production image later.
          image: 480151323504.dkr.ecr.us-east-1.amazonaws.com/customer-transaction-prediction:latest

          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8000

          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3